services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:17.0-bookworm"
    volumes:
       - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
    postgres_data: