apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nexo-deployment
  labels:
    app: nexo
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: nexo
  template:
    metadata:
      labels:
        app: nexo
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-postgres-config
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-password
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: {{ .Release.Name }}-postgres
