apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nexo-service
spec:
  type: NodePort
  selector:
    app: nexo
  ports:
    - port: {{ .Values.app.containerPort }}
      targetPort: {{ .Values.app.containerPort }}