name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER_IMAGE: ilniko/nexo-devops
  TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: '${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}'
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        if: github.event_name == 'pull_request'
        with:
          image-ref: '${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      -
        name: Build and push
        uses: docker/build-push-action@v6
        if: github.event_name == 'push'
        with:
          platforms: linux/amd64
          push: true
          tags: '${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}'